config_version: 1
task:
  type: multiclass
data:
  path: examples/data/iris_multiclass.csv
  target: species
split:
  type: stratified
  n_splits: 5
  seed: 42
train:
  num_boost_round: 300
  auto_class_weight: true
  lgb_params:
    learning_rate: 0.05
    num_leaves: 31
    max_depth: -1
    min_child_samples: 20
    subsample: 1.0
    colsample_bytree: 1.0
    reg_alpha: 0.0
    reg_lambda: 0.0
  early_stopping_rounds: 100
  seed: 42
tuning:
  enabled: false
export:
  artifact_dir: artifacts
